### ISSUE TITLE
Ignore quoted text.

### ISSUE THREAD

**Issue by 0xWDG** [AuroraEditor/AuroraEditorDiscordBot#4]
### Description

Ignore quoted text.

### To Reproduce

-

### Expected behavior

Ignore quoted text.

### Version information

-

**Comment by aurora-care-bear** [comment]
Thanks for submitting a issue!
to assign this issue to yourself please comment `@aurora-care-bear please assign me`

**Comment by 0xWDG** [comment]
Fixed in https://github.com/AuroraEditor/Aurora-Editor-Bot/commit/20275e25af130119a6fd29a41e722374d53959e5
